package com.assignment.model;


import io.swagger.v3.oas.annotations.media.Schema;
import org.hibernate.annotations.UpdateTimestamp;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.math.BigDecimal;
import java.sql.Timestamp;

@Entity
@Table(name="stock")
public class Stock {

    @Schema(description = "Autogenerated Unique identifier.")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Schema(description = "Current price of the stock.",
            example = "100", required = true, type ="number" ,format="float" )
    @NotBlank
    @NotNull
    private BigDecimal currentPrice;

    @Schema(description = "Name of the stock.",
            example = "Computer", required = true, type ="string")
    @NotBlank
    @NotEmpty
    @Size(max = 100)
    @NotNull
    private String name;

    @Schema(description = "Autogenerated last updated timestamp.")
    @UpdateTimestamp
    private Timestamp lastUpdatedTimestamp;

    public Timestamp getLastUpdatedTimestamp() {
        return lastUpdatedTimestamp;
    }

    public void setLastUpdatedTimestamp(Timestamp lastUpdatedTimestamp) {
        this.lastUpdatedTimestamp = lastUpdatedTimestamp;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public BigDecimal getCurrentPrice() {
        return currentPrice;
    }

    public void setCurrentPrice(BigDecimal currentPrice) {
        this.currentPrice = currentPrice;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
